#!/bin/sh

PATH=/opt/fcc/bin:$PATH
OPT="-v -Os -I. -DTEST"
CCRUN="../chibicc $OPT "

s=$(basename $1 .c)
echo  "compiling:" $s
echo $CCRUN -o $s.bin $s.c
$CCRUN -o $s.bin $s.c common.c
$CCRUN -S $s.c
err=$?
if [ $err -ne 0 ] ; then
	echo $err
	rm -f $s.o $s.s $s.bin
	exit $err;
fi
echo emu6800 -d 6800 $s.bin $s.map
emu6800 6800 $s.bin $s.map
ret=$?
echo $?
exit $ret
