#!/bin/sh

PATH=/opt/fcc/bin:$PATH
OPT="-v -I. -DTEST"

OPT_O="-Os"
while true; do
  case "$1" in
  -O0|-O1|-O2|-Os)
    OPT_O=$1
    shift
    ;;
  *)
    break
    ;;
  esac
done

CCRUN="../chibicc $OPT $OPT_O "

s=$(basename $1 .c)
echo  "compiling:" $s
echo $CCRUN -o $s.bin $s.c common.c -lm
$CCRUN -o $s.bin $s.c common.c -lm
$CCRUN -S $s.c
err=$?
if [ $err -ne 0 ] ; then
	echo $err
	rm -f $s.o $s.s $s.bin
	exit $err;
fi
ls -l $s.bin
echo emu6800 -d 6800 $s.bin $s.map
emu6800 6800 $s.bin $s.map
ret=$?
echo $?
exit $ret
